"""Add reconciliation models

Revision ID: 64304f9c41e2
Revises: a573c13b9e91
Create Date: 2026-04-10 10:07:07.057925

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '64304f9c41e2'
down_revision: Union[str, Sequence[str], None] = 'a573c13b9e91'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('internal_transfers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('movement_out_id', sa.Integer(), nullable=False),
    sa.Column('company_from_id', sa.Integer(), nullable=False),
    sa.Column('movement_in_id', sa.Integer(), nullable=False),
    sa.Column('company_to_id', sa.Integer(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('transfer_date', sa.Date(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('validated_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['company_from_id'], ['companies.id'], ),
    sa.ForeignKeyConstraint(['company_to_id'], ['companies.id'], ),
    sa.ForeignKeyConstraint(['movement_in_id'], ['bank_movements.id'], ),
    sa.ForeignKeyConstraint(['movement_out_id'], ['bank_movements.id'], ),
    sa.ForeignKeyConstraint(['validated_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_internal_transfers_id'), 'internal_transfers', ['id'], unique=False)
    op.create_index(op.f('ix_internal_transfers_movement_in_id'), 'internal_transfers', ['movement_in_id'], unique=False)
    op.create_index(op.f('ix_internal_transfers_movement_out_id'), 'internal_transfers', ['movement_out_id'], unique=False)
    op.create_index(op.f('ix_internal_transfers_status'), 'internal_transfers', ['status'], unique=False)
    op.create_index(op.f('ix_internal_transfers_transfer_date'), 'internal_transfers', ['transfer_date'], unique=False)
    op.create_table('reconciliations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('movement_id', sa.Integer(), nullable=False),
    sa.Column('target_type', sa.String(), nullable=True),
    sa.Column('target_id', sa.Integer(), nullable=True),
    sa.Column('score', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('reason_code', sa.String(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['movement_id'], ['bank_movements.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_reconciliations_id'), 'reconciliations', ['id'], unique=False)
    op.create_index(op.f('ix_reconciliations_movement_id'), 'reconciliations', ['movement_id'], unique=False)
    op.create_index(op.f('ix_reconciliations_status'), 'reconciliations', ['status'], unique=False)
    op.create_index(op.f('ix_reconciliations_target_id'), 'reconciliations', ['target_id'], unique=False)
    op.create_index(op.f('ix_reconciliations_target_type'), 'reconciliations', ['target_type'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_reconciliations_target_type'), table_name='reconciliations')
    op.drop_index(op.f('ix_reconciliations_target_id'), table_name='reconciliations')
    op.drop_index(op.f('ix_reconciliations_status'), table_name='reconciliations')
    op.drop_index(op.f('ix_reconciliations_movement_id'), table_name='reconciliations')
    op.drop_index(op.f('ix_reconciliations_id'), table_name='reconciliations')
    op.drop_table('reconciliations')
    op.drop_index(op.f('ix_internal_transfers_transfer_date'), table_name='internal_transfers')
    op.drop_index(op.f('ix_internal_transfers_status'), table_name='internal_transfers')
    op.drop_index(op.f('ix_internal_transfers_movement_out_id'), table_name='internal_transfers')
    op.drop_index(op.f('ix_internal_transfers_movement_in_id'), table_name='internal_transfers')
    op.drop_index(op.f('ix_internal_transfers_id'), table_name='internal_transfers')
    op.drop_table('internal_transfers')
    # ### end Alembic commands ###
