"""Add bank movement model

Revision ID: a573c13b9e91
Revises: e792ff807dae
Create Date: 2026-04-10 10:04:47.430474

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a573c13b9e91'
down_revision: Union[str, Sequence[str], None] = 'e792ff807dae'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bank_movements',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('bank_account_id', sa.Integer(), nullable=False),
    sa.Column('batch_id', sa.Integer(), nullable=False),
    sa.Column('movement_date', sa.Date(), nullable=False),
    sa.Column('description_raw', sa.String(), nullable=False),
    sa.Column('description_normalized', sa.String(), nullable=False),
    sa.Column('document_no', sa.String(), nullable=True),
    sa.Column('credit_amount', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('debit_amount', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('balance_after', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('dedup_key', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['bank_account_id'], ['bank_accounts.id'], ),
    sa.ForeignKeyConstraint(['batch_id'], ['import_batches.id'], ),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_bank_movements_bank_account_id'), 'bank_movements', ['bank_account_id'], unique=False)
    op.create_index(op.f('ix_bank_movements_company_id'), 'bank_movements', ['company_id'], unique=False)
    op.create_index(op.f('ix_bank_movements_dedup_key'), 'bank_movements', ['dedup_key'], unique=True)
    op.create_index(op.f('ix_bank_movements_description_normalized'), 'bank_movements', ['description_normalized'], unique=False)
    op.create_index(op.f('ix_bank_movements_document_no'), 'bank_movements', ['document_no'], unique=False)
    op.create_index(op.f('ix_bank_movements_id'), 'bank_movements', ['id'], unique=False)
    op.create_index(op.f('ix_bank_movements_movement_date'), 'bank_movements', ['movement_date'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_bank_movements_movement_date'), table_name='bank_movements')
    op.drop_index(op.f('ix_bank_movements_id'), table_name='bank_movements')
    op.drop_index(op.f('ix_bank_movements_document_no'), table_name='bank_movements')
    op.drop_index(op.f('ix_bank_movements_description_normalized'), table_name='bank_movements')
    op.drop_index(op.f('ix_bank_movements_dedup_key'), table_name='bank_movements')
    op.drop_index(op.f('ix_bank_movements_company_id'), table_name='bank_movements')
    op.drop_index(op.f('ix_bank_movements_bank_account_id'), table_name='bank_movements')
    op.drop_table('bank_movements')
    # ### end Alembic commands ###
