"""Add adjustments and closings

Revision ID: a9eefafaa911
Revises: 64304f9c41e2
Create Date: 2026-04-10 10:09:57.303351

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a9eefafaa911'
down_revision: Union[str, Sequence[str], None] = '64304f9c41e2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('daily_closings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('closing_date', sa.Date(), nullable=False),
    sa.Column('flow_balance', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('bank_balance', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('difference_amount', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('notes', sa.String(), nullable=True),
    sa.Column('closed_by', sa.Integer(), nullable=False),
    sa.Column('closed_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('reopened_by', sa.Integer(), nullable=True),
    sa.Column('reopened_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('reopen_reason', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['closed_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.ForeignKeyConstraint(['reopened_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_daily_closings_closing_date'), 'daily_closings', ['closing_date'], unique=False)
    op.create_index(op.f('ix_daily_closings_company_id'), 'daily_closings', ['company_id'], unique=False)
    op.create_index(op.f('ix_daily_closings_id'), 'daily_closings', ['id'], unique=False)
    op.create_table('manual_adjustments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('adjustment_date', sa.Date(), nullable=False),
    sa.Column('kind', sa.String(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.Column('category_id', sa.String(), nullable=True),
    sa.Column('reason', sa.String(), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_manual_adjustments_adjustment_date'), 'manual_adjustments', ['adjustment_date'], unique=False)
    op.create_index(op.f('ix_manual_adjustments_company_id'), 'manual_adjustments', ['company_id'], unique=False)
    op.create_index(op.f('ix_manual_adjustments_id'), 'manual_adjustments', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_manual_adjustments_id'), table_name='manual_adjustments')
    op.drop_index(op.f('ix_manual_adjustments_company_id'), table_name='manual_adjustments')
    op.drop_index(op.f('ix_manual_adjustments_adjustment_date'), table_name='manual_adjustments')
    op.drop_table('manual_adjustments')
    op.drop_index(op.f('ix_daily_closings_id'), table_name='daily_closings')
    op.drop_index(op.f('ix_daily_closings_company_id'), table_name='daily_closings')
    op.drop_index(op.f('ix_daily_closings_closing_date'), table_name='daily_closings')
    op.drop_table('daily_closings')
    # ### end Alembic commands ###
