"""Add erp models

Revision ID: e792ff807dae
Revises: c76f088b7853
Create Date: 2026-04-10 10:00:27.835775

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e792ff807dae'
down_revision: Union[str, Sequence[str], None] = 'c76f088b7853'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('import_batches',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('source_type', sa.String(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('bank_account_id', sa.Integer(), nullable=True),
    sa.Column('period_start', sa.Date(), nullable=True),
    sa.Column('period_end', sa.Date(), nullable=True),
    sa.Column('file_hash', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['bank_account_id'], ['bank_accounts.id'], ),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_import_batches_company_id'), 'import_batches', ['company_id'], unique=False)
    op.create_index(op.f('ix_import_batches_file_hash'), 'import_batches', ['file_hash'], unique=False)
    op.create_index(op.f('ix_import_batches_id'), 'import_batches', ['id'], unique=False)
    op.create_index(op.f('ix_import_batches_source_type'), 'import_batches', ['source_type'], unique=False)
    op.create_table('accounts_payable',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('batch_id', sa.Integer(), nullable=False),
    sa.Column('external_ref', sa.String(), nullable=True),
    sa.Column('supplier_name', sa.String(), nullable=False),
    sa.Column('document_no', sa.String(), nullable=True),
    sa.Column('due_date', sa.Date(), nullable=False),
    sa.Column('due_date_real', sa.Date(), nullable=True),
    sa.Column('amount', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('history', sa.String(), nullable=True),
    sa.Column('raw_data', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['batch_id'], ['import_batches.id'], ),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_accounts_payable_company_id'), 'accounts_payable', ['company_id'], unique=False)
    op.create_index(op.f('ix_accounts_payable_document_no'), 'accounts_payable', ['document_no'], unique=False)
    op.create_index(op.f('ix_accounts_payable_due_date'), 'accounts_payable', ['due_date'], unique=False)
    op.create_index(op.f('ix_accounts_payable_external_ref'), 'accounts_payable', ['external_ref'], unique=False)
    op.create_index(op.f('ix_accounts_payable_id'), 'accounts_payable', ['id'], unique=False)
    op.create_index(op.f('ix_accounts_payable_status'), 'accounts_payable', ['status'], unique=False)
    op.create_index(op.f('ix_accounts_payable_supplier_name'), 'accounts_payable', ['supplier_name'], unique=False)
    op.create_table('accounts_receivable',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('batch_id', sa.Integer(), nullable=False),
    sa.Column('external_ref', sa.String(), nullable=True),
    sa.Column('customer_name', sa.String(), nullable=False),
    sa.Column('document_no', sa.String(), nullable=True),
    sa.Column('due_date', sa.Date(), nullable=False),
    sa.Column('due_date_real', sa.Date(), nullable=True),
    sa.Column('amount', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('history', sa.String(), nullable=True),
    sa.Column('raw_data', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['batch_id'], ['import_batches.id'], ),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_accounts_receivable_company_id'), 'accounts_receivable', ['company_id'], unique=False)
    op.create_index(op.f('ix_accounts_receivable_customer_name'), 'accounts_receivable', ['customer_name'], unique=False)
    op.create_index(op.f('ix_accounts_receivable_document_no'), 'accounts_receivable', ['document_no'], unique=False)
    op.create_index(op.f('ix_accounts_receivable_due_date'), 'accounts_receivable', ['due_date'], unique=False)
    op.create_index(op.f('ix_accounts_receivable_external_ref'), 'accounts_receivable', ['external_ref'], unique=False)
    op.create_index(op.f('ix_accounts_receivable_id'), 'accounts_receivable', ['id'], unique=False)
    op.create_index(op.f('ix_accounts_receivable_status'), 'accounts_receivable', ['status'], unique=False)
    op.create_table('title_settlements',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title_type', sa.String(), nullable=False),
    sa.Column('title_id', sa.Integer(), nullable=False),
    sa.Column('settlement_date', sa.Date(), nullable=False),
    sa.Column('amount_paid', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('bank_label', sa.String(), nullable=True),
    sa.Column('source_batch_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['source_batch_id'], ['import_batches.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_title_settlements_id'), 'title_settlements', ['id'], unique=False)
    op.create_index(op.f('ix_title_settlements_settlement_date'), 'title_settlements', ['settlement_date'], unique=False)
    op.create_index(op.f('ix_title_settlements_title_id'), 'title_settlements', ['title_id'], unique=False)
    op.create_index(op.f('ix_title_settlements_title_type'), 'title_settlements', ['title_type'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_title_settlements_title_type'), table_name='title_settlements')
    op.drop_index(op.f('ix_title_settlements_title_id'), table_name='title_settlements')
    op.drop_index(op.f('ix_title_settlements_settlement_date'), table_name='title_settlements')
    op.drop_index(op.f('ix_title_settlements_id'), table_name='title_settlements')
    op.drop_table('title_settlements')
    op.drop_index(op.f('ix_accounts_receivable_status'), table_name='accounts_receivable')
    op.drop_index(op.f('ix_accounts_receivable_id'), table_name='accounts_receivable')
    op.drop_index(op.f('ix_accounts_receivable_external_ref'), table_name='accounts_receivable')
    op.drop_index(op.f('ix_accounts_receivable_due_date'), table_name='accounts_receivable')
    op.drop_index(op.f('ix_accounts_receivable_document_no'), table_name='accounts_receivable')
    op.drop_index(op.f('ix_accounts_receivable_customer_name'), table_name='accounts_receivable')
    op.drop_index(op.f('ix_accounts_receivable_company_id'), table_name='accounts_receivable')
    op.drop_table('accounts_receivable')
    op.drop_index(op.f('ix_accounts_payable_supplier_name'), table_name='accounts_payable')
    op.drop_index(op.f('ix_accounts_payable_status'), table_name='accounts_payable')
    op.drop_index(op.f('ix_accounts_payable_id'), table_name='accounts_payable')
    op.drop_index(op.f('ix_accounts_payable_external_ref'), table_name='accounts_payable')
    op.drop_index(op.f('ix_accounts_payable_due_date'), table_name='accounts_payable')
    op.drop_index(op.f('ix_accounts_payable_document_no'), table_name='accounts_payable')
    op.drop_index(op.f('ix_accounts_payable_company_id'), table_name='accounts_payable')
    op.drop_table('accounts_payable')
    op.drop_index(op.f('ix_import_batches_source_type'), table_name='import_batches')
    op.drop_index(op.f('ix_import_batches_id'), table_name='import_batches')
    op.drop_index(op.f('ix_import_batches_file_hash'), table_name='import_batches')
    op.drop_index(op.f('ix_import_batches_company_id'), table_name='import_batches')
    op.drop_table('import_batches')
    # ### end Alembic commands ###
